# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('sensor', models.CharField(max_length=60)),
                ('payload', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-log_time'],
            },
        ),
    ]
