# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schemes', '0001_initial'),
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('gps_longitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gps_latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('city', models.CharField(max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fieldlog',
            options={'ordering': ['-datetime'], 'verbose_name': 'fieldlog', 'verbose_name_plural': 'fieldlogs'},
        ),
        migrations.RemoveField(
            model_name='fieldlog',
            name='log_time',
        ),
        migrations.RemoveField(
            model_name='fieldlog',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='fieldlog',
            name='sensor',
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f01',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f02',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f03',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f04',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f05',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f06',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f07',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f08',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f09',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f10',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f11',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f12',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f13',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f14',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f15',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f16',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f17',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f18',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f19',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='f20',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fieldlog',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schemes.Scheme'),
        ),
    ]
