# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 15:47
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

fixture = 'init_fields.json'
call_command('loaddata', fixture, app_label='fields')

class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_fieldlog_field'),
    ]

    operations = [
    ]
